export enum Escolaridade {
    ENFUNDAMENTALINCOMPLETO = 'ENFUNDAMENTALINCOMPLETO',
    ENFUNDAMENTALCOMPLETO = 'ENFUNDAMENTALCOMPLETO',
    ENMEDIOINCOMPLETO = 'ENMEDIOINCOMPLETO',
    ENMEDIOCOMPLETO = 'ENMEDIOCOMPLETO',
    CURSANDO = 'CURSANDO',
    ENSUPERIORCOMP = 'ENSUPERIORCOMP',
    NULL = 'NULL'
}